name: oneware
base: core24

confinement: classic

adopt-info: oneware

icon: ./studio/OneWare.Studio/Assets/com.one_ware.OneWare.svg

apps:
  oneware:
    command: ./OneWareStudio
    common-id: com.one_ware.OneWare
    desktop: ./com.one_ware.OneWare.desktop
    
parts:
  oneware:
    plugin: dump
    source: .
    parse-info: [studio/OneWare.Studio.Desktop/com.one_ware.OneWare.metainfo.xml]
    override-build: |
      export TZ=Europe/Berlin
      ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
      curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --version latest
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$DOTNET_ROOT:$DOTNET_ROOT/tools
      cd studio/OneWare.Studio.Desktop
      dotnet publish -r linux-x64 -c Release -o $SNAPCRAFT_PART_INSTALL
      chmod +x $SNAPCRAFT_PART_INSTALL/OneWareStudio
      chmod +x $SNAPCRAFT_PART_INSTALL/AsmichiChildProcessHelper

      sed -i 's|^Icon=.*$|Icon=${SNAP}/meta/gui/com.one_ware.OneWare.svg|' $SNAPCRAFT_PART_INSTALL/com.one_ware.OneWare.desktop
    stage-packages:
      - libgtk-3-0
      - libx11-6
      - libice6
      - libsm6
