name: Publish Studio Desktop for Linux in Snap Store

on:
  workflow_dispatch:

jobs:
  deploy-snapcraft:
    name: Deploy for Snap Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: mavrosxristoforos/get-xml-info@2.0
        name: Get Version
        id: get-oneware-version
        with:
          xml-file: './build/props/Base.props'
          xpath: "//*[local-name()='Project']/*[local-name()='PropertyGroup']/*[local-name()='StudioVersion']"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Snap  
        uses: snapcore/action-build@v1  
        id: build
      - name : Upload Snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_ONEWARE }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable