name: Publish OneWare Studio Web

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x 
      - name: Install Wasm-Tools
        run: dotnet workload install wasm-tools
      - name: Publish
        run: dotnet publish ./demo/OneWare.Demo.Browser/OneWare.Demo.Browser.csproj -c Release
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: w01e537f.kasserver.com
          username: w01e537f
          password: ${{ secrets.ONEWARE_STUDIO_FTP }}
          local-dir: ./demo/OneWare.Demo.Browser/bin/Release/net8.0/browser-wasm/AppBundle/
          server-dir: demo.oneware.studio/
