name: Deploy OneWare Studio Desktop

on:
  workflow_dispatch:

jobs:
  # Build MSI and Upload to CDN
  deploy-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: mavrosxristoforos/get-xml-info@2.0
        name: Get Version
        id: get-oneware-version
        with:
          xml-file: './build/props/Base.props'
          xpath: "//*[local-name()='Project']/*[local-name()='PropertyGroup']/*[local-name()='Version']"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install Wix
        run: dotnet tool install --global wix
      - name: Publish
        run: dotnet build ./studio/OneWare.Studio.Desktop.WindowsInstaller/OneWare.Studio.Desktop.WindowsInstaller.wixproj -c Release -r win-x64 -o ./out
      - name: Make Version Dir
        run: mkdir ./${{ steps.get-oneware-version.outputs.info }}
      - name: Move .msi
        run: move ./out/en-us/OneWareStudio.WindowsInstaller.msi ./${{ steps.get-oneware-version.outputs.info }}/OneWareStudio-${{ steps.get-oneware-version.outputs.info }}-x64.msi
      - name: Sign Installer (SKIP)
        run: echo "TODO"
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: w01e537f.kasserver.com
          username: w01e537f
          password: ${{ secrets.ONEWARE_FTP }}
          local-dir: ./${{ steps.get-oneware-version.outputs.info }}/
          server-dir: ./cdn.one-ware.com/onewarestudio/${{ steps.get-oneware-version.outputs.info }}/