name: Publish Studio Web

on:
  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Install Wasm-Tools
        run: dotnet workload install wasm-tools
      - name: Publish
        run: dotnet publish ./studio/OneWare.Studio.Browser/OneWare.Studio.Browser.csproj -c Release -o ./out
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: w01ec151.kasserver.com
          username: w01ec151
          password: ${{ secrets.ONEWARE_FTP }}
          local-dir: ./out/wwwroot/
          server-dir: studio.one-ware.com/
