name: Deploy OneWare Studio Desktop

on:
  workflow_dispatch:

jobs:
  # Build MSI and publish
  deploy-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x 
      - name: Publish
        run: dotnet build ./studio/OneWare.Studio.Desktop.WindowsInstaller/OneWare.Studio.Desktop.WindowsInstaller.wixproj -c Release -r win-x64 -o ./out
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: w01e537f.kasserver.com
          username: w01e537f
          password: ${{ secrets.ONEWARE_FTP }}
          local-dir: ./out/en-us
          server-dir: demo.oneware.studio/
