name: Publish Studio Desktop for Linux in Flathub

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Publish Studio Desktop ]
    types:
      - completed

jobs:
  deploy-flathub:
    name: Deploy in Flathub
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive