# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# This is run on the OneWare Build server weekly to check the 

name: Test Build Server

on:
  schedule: 
    - cron: '0 5 * * 5'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Workload Restore
        run: dotnet workload restore
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
